[build]
  base = "/"
  command = "npm run build"
  publish = "build"
  functions = ".netlify/functions"

[build.environment]
  NODE_VERSION = "18"

# Handle React Router routing - redirect all paths to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[dev]
  framework = "create-react-app"
  targetPort = 3000
  functionsPort = 9999
  autoLaunch = true
